### ISSUE TITLE
项目设计

### ISSUE THREAD

**Issue by ericlfay** [ericlfay/website#2]
设计整个项目思路 架构 时间段

**Comment by ericlfay** [comment]
设计思路

**Comment by ericlfay** [comment]
1 用户 
2 内容
3 评论

**Comment by ericlfay** [comment]
反喷 当一个喷子猛烈的喷另外一个人时 被喷的这个人可以发起投票 看这个人是不是喷的有道理 投票有时间限制 时间限制过了 判断是否被删除

**Comment by ericlfay** [comment]
![066d57d3-7e4f-4fc5-8a94-888c5ee95e25](https://cloud.githubusercontent.com/assets/18476398/26567292/a3a27864-452c-11e7-8b27-38fc79e69874.png)
项目基础架构 有空你们也看看有需要增减的东西吗

**Comment by Dylan-fy** [comment]
网站的名字也得想好吧，然后就是内容往站名靠了，主题明确。对于这个网站貌似架构也就这些了，主要还是内容的充实。感觉现在有匿名的需求，就是不知道可不可行。

**Comment by Dylan-fy** [comment]
对于匿名这一块可以实名注册，选择性匿名发言

**Comment by ericlfay** [comment]
添加撤回功能
